spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HotelManagementSystem
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
   host: smtp.gmail.com
   port: 587
   username: tumiraduli@gmail.com
   password: yqrm tjue dogq qsqg
   properties:
      mail:
       smtp:
        auth: true
        starttls.enable: true

#
#  security:
#    user:
#      name: tumiraduli@gmail.com
#      password: 1234

